AWSTemplateFormatVersion: '2010-09-09'

Description: S3 Bucket for Lambda function template with YAML - S3 Bucket Definition

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: debugroom-sample-lambda-errorhandling-cfn-bucket
      AccessControl: "Private"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True

Outputs:
  S3Bucket:
    Description: Lambda deploy S3 bucket name
    Value: !Ref S3Bucket
    Export:
      Name: debugroom-sample-lambda-errorhandling-s3bucket

  S3BucketArn:
    Description: S3 for Lambda bucket arn
    Value: !GetAtt S3Bucket.Arn
    Export:
      Name: debugroom-sample-lambda-errorhandling-s3bucket-arn
